import {
  sold1,
  sold2,
  sold3,
  sold_11,
  sold_12,
  sold_13,
  sold_21,
  sold_22,
  sold_23,
  sold_24,
  sold_25,
  sold_26,
} from "../assets";

export interface Assets {
  id: number;
  img: string;
  name: string;
  location?: string;
  category: string;
  desc: string;
  purchased: string;
  sale: string;
  holding: string;
  purchasePrice: string;
  cost: string;
  salePrice: string;
  profit: string;
  roi: string;
  coc: string;
  imgs: string[];
}

export const assets: Assets[] = [
  // Properties
  {
    id: 1,
    img: sold1,
    desc: "This property, purchased on July 18, 2024, and sold after a 4.5-month holding period, achieved a profit of $15,970 from an out-of-pocket investment of $31,110, resulting in an impressive ROl of 51.3%. The project demonstrates efficient execution and strategic management, delivering strong returns within a short timeframe",
    category: "Sold",
    location: "Maryland",
    name: "110 Long Ave Salisbury",
    purchased: "July 18, 2024",
    sale: "December 6, 2024",
    holding: "4 1/2 Months",
    purchasePrice: "$135,000.00",
    cost: "$117,906.12",
    salePrice: "$290,000.00",
    profit: "$37,093.88",
    roi: "14.7%",
    coc: "",
    imgs: [sold_11, sold_12, sold_13],
  },

  {
    id: 2,
    img: sold2,
    desc: "This property was purchased on October 2, 2024, and sold after holding for 2 months and 25 days. It achieved a profit of $22,282.35 from an out-of-pocket investment of $32,130.07, resulting in an impressive ROl of 69.35%. The project showcases efficient execution and strategic management, delivering strong returns within a short timeframe.",
    category: "Sold",
    location: "Maryland",
    name: "603 Sherwood Cir",
    purchased: "Oct 2,2024",
    sale: "December 27, 2024",
    holding: "2 Months 25 days",
    purchasePrice: "$147,000",
    cost: "$100,717.65",
    salePrice: "$270,000",
    profit: "$22,282.35",
    roi: "9%",
    coc: "",
    imgs: [sold_21, sold_22, sold_23, sold_24, sold_25, sold_26],
  },
  {
    id: 3,
    img: sold3,
    desc: "This property was purchased on January 24, 2025, and sold on February 19, 2025, with a holding period of 26 days. Originally intended as a full flip, we identified an eager buyer who wanted the property as-is, allowing us to pivot and secure a strong return with minimal renovation.",
    category: "Sold",
    location: "Maryland",
    name: "2910 Jesterville Rd",
    purchased: "January 24, 2025",
    sale: "February 19, 2025",
    holding: "26 days",
    purchasePrice: "$189,000",
    cost: "$14,736.49",
    salePrice: "$250,000",
    profit: "$46,263.51",
    roi: "22.7%",
    coc: "",
    imgs: [sold3],
  },
  // {
  //   id: 4,
  //   img: hero8,
  //   desc: "Gated community with state-of-the-art amenities.",
  //   category: "Current",
  //   location: "Charlotte, NC",
  //   name: "Queen’s Court Residences",
  //   purchased: "2020",
  // },
  // {
  //   id: 5,
  //   img: hero7,
  //   desc: "Elegant apartments with waterfront access.",
  //   category: "Current",
  //   location: "Tampa, FL",
  //   name: "Harbor View Lofts",
  //   purchased: "2024",
  // },
  // {
  //   id: 6,
  //   img: hero6,
  //   desc: "Suburban homes with large backyards.",
  //   category: "Current",
  //   location: "Columbus, OH",
  //   name: "Maple Grove Estates",
  //   purchased: "2019",
  // },
  // {
  //   id: 7,
  //   img: hero5,
  //   desc: "High-rise apartments in a cultural district.",
  //   category: "Current",
  //   location: "Nashville, TN",
  //   name: "Music City Towers",
  //   purchased: "2025",
  // },
  // {
  //   id: 8,
  //   img: hero4,
  //   desc: "Sustainable living spaces with solar panels.",
  //   category: "Current",
  //   location: "Portland, OR",
  //   name: "Green Leaf Residences",
  //   purchased: "2023",
  // },
  // {
  //   id: 9,
  //   img: hero2,
  //   desc: "Minimalist lofts with industrial charm.",
  //   category: "Current",
  //   location: "Minneapolis, MN",
  //   name: "Stone Arch Lofts",
  //   purchased: "2021",
  // },
  // {
  //   id: 10,
  //   img: hero11,
  //   desc: "Modern urban apartments with rooftop terraces.",
  //   category: "Current",
  //   location: "Denver, CO",
  //   name: "Mile High Flats",
  //   purchased: "2022",
  // },
  // {
  //   id: 11,
  //   img: hero10,
  //   desc: "Luxury penthouses with smart home features.",
  //   category: "Current",
  //   location: "Atlanta, GA",
  //   name: "Peachtree Plaza Residences",
  //   purchased: "2020",
  // },

  // For Sale Properties
  // {
  //   id: 1,
  //   img: hero2,
  //   desc: "Contemporary townhouses with private patios.",
  //   category: "For Sale",
  //   location: "Seattle, WA",
  //   name: "Emerald Bay Townhomes",
  //   purchased: "2022",
  // },
  // {
  //   id: 2,
  //   img: hero4,
  //   desc: "Renovated historic homes with modern finishes.",
  //   category: "For Sale",
  //   location: "Boston, MA",
  //   name: "Beacon Hill Estates",
  //   purchased: "2021",
  // },
  // {
  //   id: 3,
  //   img: hero6,
  //   desc: "Stylish lofts in a growing arts district.",
  //   category: "For Sale",
  //   location: "Austin, TX",
  //   name: "SoCo Loft Collection",
  //   purchased: "2023",
  // },
  // {
  //   id: 4,
  //   img: hero7,
  //   desc: "Affordable family homes in a peaceful suburb.",
  //   category: "For Sale",
  //   location: "Indianapolis, IN",
  //   name: "Maplewood Residences",
  //   purchased: "2020",
  // },
  // {
  //   id: 5,
  //   img: hero8,
  //   desc: "Luxury condos with smart home technology.",
  //   category: "For Sale",
  //   location: "Miami, FL",
  //   name: "Azure Sky Towers",
  //   purchased: "2024",
  // },
  // {
  //   id: 6,
  //   img: hero9,
  //   desc: "Penthouse apartments with private rooftop access.",
  //   category: "For Sale",
  //   location: "Las Vegas, NV",
  //   name: "The Strip Residences",
  //   purchased: "2021",
  // },
  // {
  //   id: 7,
  //   img: hero10,
  //   desc: "Beachfront villas with stunning ocean views.",
  //   category: "For Sale",
  //   location: "Santa Monica, CA",
  //   name: "Coastal Breeze Villas",
  //   purchased: "2025",
  // },
  // {
  //   id: 8,
  //   img: hero5,
  //   desc: "Urban lofts in a revitalized district.",
  //   category: "For Sale",
  //   location: "Detroit, MI",
  //   name: "Midtown Revival Lofts",
  //   purchased: "2023",
  // },
  // {
  //   id: 9,
  //   img: hero11,
  //   desc: "Classic brownstones in a historic neighborhood.",
  //   category: "For Sale",
  //   location: "Brooklyn, NY",
  //   name: "Prospect Park Brownstones",
  //   purchased: "2019",
  // },
  // {
  //   id: 10,
  //   img: hero2,
  //   desc: "Contemporary apartments near downtown attractions.",
  //   category: "For Sale",
  //   location: "Phoenix, AZ",
  //   name: "Desert Ridge Flats",
  //   purchased: "2022",
  // },
  // {
  //   id: 11,
  //   img: hero4,
  //   desc: "Eco-friendly homes with energy-efficient designs.",
  //   category: "For Sale",
  //   location: "Boulder, CO",
  //   name: "Mountain Peak EcoHomes",
  //   purchased: "2020",
  // },

  // Sold Properties
  // {
  //   id: 1,
  //   img: hero7,
  //   desc: "Classic homes in a tree-lined community.",
  //   category: "Sold",
  //   location: "Madison, WI",
  //   name: "Lakewood Estates",
  //   purchased: "2018",
  // },
  // {
  //   id: 2,
  //   img: hero8,
  //   desc: "Upscale apartments with luxury finishes.",
  //   category: "Sold",
  //   location: "San Francisco, CA",
  //   name: "Golden Gate Heights",
  //   purchased: "2019",
  // },
  // {
  //   id: 3,
  //   img: hero5,
  //   desc: "Mid-century modern homes with large patios.",
  //   category: "Sold",
  //   location: "Sacramento, CA",
  //   name: "Valley View Homes",
  //   purchased: "2021",
  // },
  // {
  //   id: 4,
  //   img: hero2,
  //   desc: "Newly built suburban houses with large yards.",
  //   category: "Sold",
  //   location: "Raleigh, NC",
  //   name: "Pinewood Meadows",
  //   purchased: "2022",
  // },
  // {
  //   id: 5,
  //   img: hero11,
  //   desc: "Lofts with industrial-style architecture.",
  //   category: "Sold",
  //   location: "St. Louis, MO",
  //   name: "Brickhouse Lofts",
  //   purchased: "2017",
  // },
  // {
  //   id: 6,
  //   img: hero10,
  //   desc: "High-rise apartments in a growing tech hub.",
  //   category: "Sold",
  //   location: "San Jose, CA",
  //   name: "Silicon Valley Residences",
  //   purchased: "2023",
  // },
  // {
  //   id: 7,
  //   img: hero9,
  //   desc: "Townhomes near top-rated schools.",
  //   category: "Sold",
  //   location: "Orlando, FL",
  //   name: "Sunshine Terrace",
  //   purchased: "2020",
  // },
  // {
  //   id: 8,
  //   img: hero2,
  //   desc: "Charming homes with historical character.",
  //   category: "Sold",
  //   location: "New Orleans, LA",
  //   name: "French Quarter Residences",
  //   purchased: "2021",
  // },
  // {
  //   id: 9,
  //   img: hero4,
  //   desc: "Sustainable housing in an eco-friendly community.",
  //   category: "Sold",
  //   location: "Boulder, CO",
  //   name: "Evergreen EcoHomes",
  //   purchased: "2019",
  // },
  // {
  //   id: 10,
  //   img: hero8,
  //   desc: "Affordable starter homes for young families.",
  //   category: "Sold",
  //   location: "Richmond, VA",
  //   name: "Riverbend Estates",
  //   purchased: "2018",
  // },
  // {
  //   id: 11,
  //   img: hero9,
  //   desc: "Modern apartments in a lively downtown area.",
  //   category: "Sold",
  //   location: "Kansas City, MO",
  //   name: "Union Square Residences",
  //   purchased: "2016",
  // },
];
