import {
  hero2,
  hero4,
  hero5,
  hero6,
  hero7,
  hero8,
  hero9,
  hero10,
  hero11,
} from "../assets";

interface Assets {
  id: number;
  img: string;
  name: string;
  location: string;
  category: string;
  desc: string;
  purchased: string;
}

export const assets: Assets[] = [
  // Current Properties
  {
    id: 1,
    img: hero11,
    desc: "Modern apartments in a vibrant city center.",
    category: "Current",
    location: "San Diego, CA",
    name: "Sunset Heights",
    purchased: "2022",
  },
  {
    id: 2,
    img: hero10,
    desc: "Luxury condos with skyline views.",
    category: "Current",
    location: "Houston, TX",
    name: "Bayou Towers",
    purchased: "2023",
  },
  {
    id: 3,
    img: hero9,
    desc: "Spacious townhomes in a serene environment.",
    category: "Current",
    location: "Phoenix, AZ",
    name: "Desert Oasis Homes",
    purchased: "2021",
  },
  {
    id: 4,
    img: hero8,
    desc: "Gated community with state-of-the-art amenities.",
    category: "Current",
    location: "Charlotte, NC",
    name: "Queen’s Court Residences",
    purchased: "2020",
  },
  {
    id: 5,
    img: hero7,
    desc: "Elegant apartments with waterfront access.",
    category: "Current",
    location: "Tampa, FL",
    name: "Harbor View Lofts",
    purchased: "2024",
  },
  {
    id: 6,
    img: hero6,
    desc: "Suburban homes with large backyards.",
    category: "Current",
    location: "Columbus, OH",
    name: "Maple Grove Estates",
    purchased: "2019",
  },
  {
    id: 7,
    img: hero5,
    desc: "High-rise apartments in a cultural district.",
    category: "Current",
    location: "Nashville, TN",
    name: "Music City Towers",
    purchased: "2025",
  },
  {
    id: 8,
    img: hero4,
    desc: "Sustainable living spaces with solar panels.",
    category: "Current",
    location: "Portland, OR",
    name: "Green Leaf Residences",
    purchased: "2023",
  },
  {
    id: 9,
    img: hero2,
    desc: "Minimalist lofts with industrial charm.",
    category: "Current",
    location: "Minneapolis, MN",
    name: "Stone Arch Lofts",
    purchased: "2021",
  },
  {
    id: 10,
    img: hero11,
    desc: "Modern urban apartments with rooftop terraces.",
    category: "Current",
    location: "Denver, CO",
    name: "Mile High Flats",
    purchased: "2022",
  },
  {
    id: 11,
    img: hero10,
    desc: "Luxury penthouses with smart home features.",
    category: "Current",
    location: "Atlanta, GA",
    name: "Peachtree Plaza Residences",
    purchased: "2020",
  },

  // For Sale Properties
  {
    id: 1,
    img: hero2,
    desc: "Contemporary townhouses with private patios.",
    category: "For Sale",
    location: "Seattle, WA",
    name: "Emerald Bay Townhomes",
    purchased: "2022",
  },
  {
    id: 2,
    img: hero4,
    desc: "Renovated historic homes with modern finishes.",
    category: "For Sale",
    location: "Boston, MA",
    name: "Beacon Hill Estates",
    purchased: "2021",
  },
  {
    id: 3,
    img: hero6,
    desc: "Stylish lofts in a growing arts district.",
    category: "For Sale",
    location: "Austin, TX",
    name: "SoCo Loft Collection",
    purchased: "2023",
  },
  {
    id: 4,
    img: hero7,
    desc: "Affordable family homes in a peaceful suburb.",
    category: "For Sale",
    location: "Indianapolis, IN",
    name: "Maplewood Residences",
    purchased: "2020",
  },
  {
    id: 5,
    img: hero8,
    desc: "Luxury condos with smart home technology.",
    category: "For Sale",
    location: "Miami, FL",
    name: "Azure Sky Towers",
    purchased: "2024",
  },
  {
    id: 6,
    img: hero9,
    desc: "Penthouse apartments with private rooftop access.",
    category: "For Sale",
    location: "Las Vegas, NV",
    name: "The Strip Residences",
    purchased: "2021",
  },
  {
    id: 7,
    img: hero10,
    desc: "Beachfront villas with stunning ocean views.",
    category: "For Sale",
    location: "Santa Monica, CA",
    name: "Coastal Breeze Villas",
    purchased: "2025",
  },
  {
    id: 8,
    img: hero5,
    desc: "Urban lofts in a revitalized district.",
    category: "For Sale",
    location: "Detroit, MI",
    name: "Midtown Revival Lofts",
    purchased: "2023",
  },
  {
    id: 9,
    img: hero11,
    desc: "Classic brownstones in a historic neighborhood.",
    category: "For Sale",
    location: "Brooklyn, NY",
    name: "Prospect Park Brownstones",
    purchased: "2019",
  },
  {
    id: 10,
    img: hero2,
    desc: "Contemporary apartments near downtown attractions.",
    category: "For Sale",
    location: "Phoenix, AZ",
    name: "Desert Ridge Flats",
    purchased: "2022",
  },
  {
    id: 11,
    img: hero4,
    desc: "Eco-friendly homes with energy-efficient designs.",
    category: "For Sale",
    location: "Boulder, CO",
    name: "Mountain Peak EcoHomes",
    purchased: "2020",
  },

  // Sold Properties
  {
    id: 1,
    img: hero7,
    desc: "Classic homes in a tree-lined community.",
    category: "Sold",
    location: "Madison, WI",
    name: "Lakewood Estates",
    purchased: "2018",
  },
  {
    id: 2,
    img: hero8,
    desc: "Upscale apartments with luxury finishes.",
    category: "Sold",
    location: "San Francisco, CA",
    name: "Golden Gate Heights",
    purchased: "2019",
  },
  {
    id: 3,
    img: hero5,
    desc: "Mid-century modern homes with large patios.",
    category: "Sold",
    location: "Sacramento, CA",
    name: "Valley View Homes",
    purchased: "2021",
  },
  {
    id: 4,
    img: hero2,
    desc: "Newly built suburban houses with large yards.",
    category: "Sold",
    location: "Raleigh, NC",
    name: "Pinewood Meadows",
    purchased: "2022",
  },
  {
    id: 5,
    img: hero11,
    desc: "Lofts with industrial-style architecture.",
    category: "Sold",
    location: "St. Louis, MO",
    name: "Brickhouse Lofts",
    purchased: "2017",
  },
  {
    id: 6,
    img: hero10,
    desc: "High-rise apartments in a growing tech hub.",
    category: "Sold",
    location: "San Jose, CA",
    name: "Silicon Valley Residences",
    purchased: "2023",
  },
  {
    id: 7,
    img: hero9,
    desc: "Townhomes near top-rated schools.",
    category: "Sold",
    location: "Orlando, FL",
    name: "Sunshine Terrace",
    purchased: "2020",
  },
  {
    id: 8,
    img: hero2,
    desc: "Charming homes with historical character.",
    category: "Sold",
    location: "New Orleans, LA",
    name: "French Quarter Residences",
    purchased: "2021",
  },
  {
    id: 9,
    img: hero4,
    desc: "Sustainable housing in an eco-friendly community.",
    category: "Sold",
    location: "Boulder, CO",
    name: "Evergreen EcoHomes",
    purchased: "2019",
  },
  {
    id: 10,
    img: hero8,
    desc: "Affordable starter homes for young families.",
    category: "Sold",
    location: "Richmond, VA",
    name: "Riverbend Estates",
    purchased: "2018",
  },
  {
    id: 11,
    img: hero9,
    desc: "Modern apartments in a lively downtown area.",
    category: "Sold",
    location: "Kansas City, MO",
    name: "Union Square Residences",
    purchased: "2016",
  },
];
