import {
  hero2,
  hero4,
  hero5,
  hero6,
  hero7,
  hero8,
  hero9,
  hero10,
  hero11,
} from "../assets";

interface Assets {
  id: number;
  img: string;
  name: string;
  location: string;
  category: string;
  desc: string;
  purchased: string;
}

export const assets: Assets[] = [
  {
    id: 1,
    img: hero2,
    desc: "Lorem ipsumss",
    category: "Current",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 2,
    img: hero4,
    desc: "Lorem ipsum",
    category: "Current",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 3,
    img: hero6,
    desc: "Lorem ipsum",
    category: "Current",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 4,
    img: hero7,
    desc: "Lorem ipsum",
    category: "Current",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 5,
    img: hero8,
    desc: "Lorem ipsum",
    category: "Current",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 6,
    img: hero9,
    desc: "Lorem ipsum",
    category: "Current",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 7,
    img: hero10,
    desc: "Lorem ipsum",
    category: "Current",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 8,
    img: hero5,
    desc: "Lorem ipsum",
    category: "Current",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 9,
    img: hero11,
    desc: "Lorem ipsum",
    category: "Current",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },

  //   For Sale
  {
    id: 1,
    img: hero2,
    desc: "Lorem ipsum",
    category: "For Sale",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 2,
    img: hero4,
    desc: "Lorem ipsum",
    category: "For Sale",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 3,
    img: hero6,
    desc: "Lorem ipsum",
    category: "For Sale",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 4,
    img: hero7,
    desc: "Lorem ipsum",
    category: "For Sale",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 5,
    img: hero8,
    desc: "Lorem ipsum",
    category: "For Sale",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 6,
    img: hero9,
    desc: "Lorem ipsum",
    category: "For Sale",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 7,
    img: hero10,
    desc: "Lorem ipsum",
    category: "For Sale",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 8,
    img: hero5,
    desc: "Lorem ipsum",
    category: "For Sale",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 9,
    img: hero11,
    desc: "Lorem ipsum",
    category: "For Sale",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },

  //   Sold
  {
    id: 1,
    img: hero2,
    desc: "Lorem ipsum",
    category: "Sold",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 2,
    img: hero4,
    desc: "Lorem ipsum",
    category: "Sold",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 3,
    img: hero6,
    desc: "Lorem ipsum",
    category: "Sold",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 4,
    img: hero7,
    desc: "Lorem ipsum",
    category: "Sold",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 5,
    img: hero8,
    desc: "Lorem ipsum",
    category: "Sold",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 6,
    img: hero9,
    desc: "Lorem ipsum",
    category: "Sold",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 7,
    img: hero10,
    desc: "Lorem ipsum",
    category: "Sold",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 8,
    img: hero5,
    desc: "Lorem ipsum",
    category: "Sold",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
  {
    id: 9,
    img: hero11,
    desc: "Lorem ipsum",
    category: "Sold",
    location: "Mt. Laurel, NJ",
    name: "Mt. Laurel Crossing",
    purchased: "2025",
  },
];
